polls/covid/urls.py
from django.urls import path
from .views import IndexView, DetailsView, ResultsView\
    ,Vote, CancelVote\
    ,RegisterUser,LoginUser,LogoutUser

app_name = 'covid'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:question_id>/', DetailsView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', Vote.as_view(), name='vote'),
    path('<int:question_id>/cancel_vote/', CancelVote.as_view(), name='cancel_vote'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutUser.as_view(), name='logout'),
]

polls/just_vote/urls.py
from django.urls import path
from .views import IndexView, DetailsView, ResultsView, \
    Vote, CancelVote, RegisterUser, LoginUser, LogoutUser

app_name = 'just_vote'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:question_id>/', DetailsView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', Vote.as_view(), name='vote'),
    path('<int:question_id>/cancel_vote/', CancelVote.as_view(), name='cancel_vote'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutUser.as_view(), name='logout'),
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('just_vote.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

polls/just_vote/models.py
import datetime
from django.conf import settings
from django.db import models


class Question(models.Model):
    """ Вопросы """
    question_text = models.CharField(max_length=200, verbose_name="Вопрос")
    pub_date = models.DateTimeField(verbose_name="Дата публикации", default=datetime.datetime.now())
    is_active = models.BooleanField(verbose_name="Опубликован", default=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = datetime.datetime.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Choice(models.Model):
    """ Ответы """
    question = models.ForeignKey(Question, verbose_name="Вопрос", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200, verbose_name="Ответы")

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = 'Ответы'
        verbose_name_plural = 'Ответы'


class UserVote(models.Model):
    """ Выбранные ответы пользователей """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Пользователь", on_delete=models.DO_NOTHING)
    choice = models.ForeignKey(Choice, verbose_name="Выбранный ответ", on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.user} - {self.choice.question}'

    class Meta:
        unique_together = [['user', 'choice']]
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

polls/just_vote/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.views.generic import ListView, TemplateView, CreateView
from django.views import View
from django.template.response import TemplateResponse
from .services import get_first_five_question, \
    get_question, check_user_vote, \
    get_count_choices, get_user_choice, Question, \
    create_user_vote, delete_user_vote
from django.shortcuts import redirect


class IndexView(ListView):
    """ Отображение списка вопросов на главной странице """
    template_name = 'just_vote/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        queryset = get_first_five_question()
        return queryset


class DetailsView(View):
    """ Отображение вариантов ответа на выбранный вопрос """
    def get(self, request, question_id):
        question = get_question(question_id)
        if check_user_vote(request, question_id) == True:
            choices = get_count_choices(question_id)
            user_choice = get_user_choice(request, question_id)
            context = {'question': question,'choices': choices,'error_message': f'Вы уже выбрали ответ "{user_choice}", \
                                                                                  выберите другой вопрос или проголосуйте заново'}

            return TemplateResponse(request, 'just_vote/results.html', context)

        return TemplateResponse(request, 'just_vote/detail.html', {'question': question})


class ResultsView(TemplateView):
    """ Отображение результатов голосования """
    model = Question
    template_name = 'just_vote/results.html'


class RegisterUser(CreateView):
    """ Регистрация """
    form_class = UserCreationForm
    template_name = 'just_vote/register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('just_vote:index')


class LoginUser(LoginView):
    """ Авторизация """
    form_class = AuthenticationForm
    template_name = 'just_vote/login.html'


class LogoutUser(LogoutView):
    """ Выход из авторизации """
    template_name = 'just_vote/index.html'


class Vote(View):
    """ Запись выбора пользователя в базу данных """
    def post(self, request, question_id):
        question = get_question(question_id)
        choice_id = request.POST.get('choice')
        if choice_id is None:
            err_context = {'question': question, 'error_message': "Вы не сделали выбор"}
            return TemplateResponse(request, 'just_vote/detail.html', err_context)
        create_user_vote(request, choice_id)
        choices = get_count_choices(question_id)
        context = {'question': question, 'choices': choices}
        return TemplateResponse(request, 'just_vote/results.html', context)


class CancelVote(View):
    """ Удаление выбора пользователя из базы данных """
    def post(self, request, question_id):
        question = get_question(question_id)
        delete_user_vote(request, question_id)
        return TemplateResponse(request, 'just_vote/detail.html', {'question': question})

polls/just_vote/templates/just_vote/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">Домой</a></li>
            </ul>
            <div class="text-end">
                {% if request.user.is_authenticated %}
                <p>Привет, {{user.username}}! <a href="{% url 'just_vote:logout' %}">
                    <button type="button" class="btn btn-outline-light me-2">Выйти</button>
                </a></p>
                {% else %}
                <a href="{% url 'just_vote:login' %}">
                    <button type="button" class="btn btn-outline-light me-2">Войти</button>
                </a>
                <a href="{% url 'just_vote:register' %}">
                    <button type="button" class="btn btn-warning">Регистрация</button>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>
<body>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>
</html>

polls/just_vote/templates/just_vote/detail.html
{% extends 'just_vote/base.html' %}
{% block title %}{{ question.question_text }}{% endblock %}
{% block content %}
<ul>
    <form action="{% url 'just_vote:vote' question.id %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Голосовать">
    </form>
</ul>
{% endblock %}

polls/just_vote/templates/just_vote/index.html
{% extends 'just_vote/base.html' %}
{% block title %}Вопросы для голосования{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <div class="list-group">
        <a href="{% url 'just_vote:detail' question.id %}" class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-question-square" viewBox="0 0 16 16">
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2
                             0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134
                             1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168
                             1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927
                             1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267
                             0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927
                             0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
            </svg>
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{{ question.question_text }}</h6>
                </div>
                <small class="opacity-50 text-nowrap">{{ question.pub_date }}</small>
            </div>
        </a>
    </div>
    {% endfor %}
</ul>
{% else %}
<h4>Нет вопросов для голосования</h4>
{% endif %}
{% else %}
<h4>Список вопросов могут просматривать только авторизованные пользователи</h4>
{% endif %}
{% endblock %}

polls/just_vote/templates/just_vote/login.html
{% extends 'just_vote/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-light me-2">Войти</button>
</form>
{% endblock %}

polls/just_vote/templates/just_vote/register.html
{% extends 'just_vote/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-light me-2">Регистрация</button>
</form>
{% endblock %}

polls/just_vote/templates/just_vote/results.html
{% extends 'just_vote/base.html' %}
{% block title %}{{ question.question_text }}{% endblock %}
{% block content %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<ul>
    {% for choice in choices %}
    <li>{{ choice.choice_text }} -> {{ choice.votes_count }}</li>
    {% endfor %}
</ul>
<form action="{% url 'just_vote:cancel_vote' question.id %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Отменить голос">
</form>
{% endblock %}